config/routes.rb
RailsChapter3::Application.routes.draw do
  get "sessions/new"

  resources :users
   
  resources :sessions, :only => [:new, :create, :destroy]



  root :to=>'pages#home'
  match '/contact', :to=>'pages#contact'
  match '/about', :to=>'pages#about'
  match '/help', :to=>'pages#help'
  match '/signup', :to=>'users#new'
  match '/signin', :to=>'sessions#new'
  match '/signout', :to=>'sessions#destroy'











end

app/models/user.rb
# == Schema Information
# Schema version: 20110111151410
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                    :length => { :maximum => 50 }
  
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :password,  :confirmation => true,
                        :presence => true,
                        :length => { :within => 6..40 }
                        
  before_save :encrypt_password  # register callback
  
  #return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    #compare encrypted_password with the encrypted version of submitted_password
    encrypted_password == encrypt(submitted_password)
  end
  
  #return a user object matching supplier email and password
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    user && user.has_password?(submitted_password) ? user : nil 
  end
  
  private
   
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.new.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title ="Sign in"
  end
  
  # create handles form submission and makes new session
  def create
    #render 'new'  # show blank forms
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      #create error message and re-render signin form
      flash.now[:error] = "Sorry your username and/or password were not correct."
      @title = "Sign in"
      render = 'new'
    else
      #sign the user in and redirect to the user's show page
    end
              
  end
  
  # accessed via HTTP DELETE, deletes a session
  def destroy
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App. You've succesfully 
                          signed up."
      redirect_to @user
    else
      @title = "Sign up"
      @user.password, @user.password_confirmation = nil
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper  # put helpers here
  # helpers are functions for use in views (remember, in Rails views are the templates!)
  
  #  return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
    
  def logo
    logo = image_tag("logo.png", :alt=>"Sample app", :class=>"round")
  end

end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {:size=>50})
    gravatar_image_tag(user.email.downcase, :alt=>user.name,
                                            :class=>'gravatar',
                                            :gravatar=>options)
  end
end

app/views/layouts/_footer.html.erb
      <footer>
        <nav class="round">
          <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://www.railstutorial.org/">News</a></li>
          </ul>
        </nav>
      </footer>

app/views/layouts/_header.html.erb
      <header>
        <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
<%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
<%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
        <!--<div class="flash <%= key %>"><%= value %></div>-->
        <%= content_tag(:div, value, :class=>"flash #{key}") %>
        <% end %>
        <%= yield %>
      </section>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
    <h1>About</h1>
    <p>About us...</p>

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>contact us...</p>

app/views/pages/help.html.erb
    <h1>Help</h1>
    <p>Help me!</p>

app/views/pages/home.html.erb
    <h1>Sample App</h1>
    <p>This is the home page for the Rails Tuts...</p>
    <%= link_to "Sign up now!", signup_path, :class=>"signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prevented you from signing up:</h2>
  <p>There were problems with the following fields:</p>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
  

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do  |f| %>
  <%= render 'shared/error_messages' %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>
<div class="actions">
  <%= f.submit "Sign up "%>
</div>
<% end %>

app/views/users/show.html.erb

<p><%= @user.email %></p>


<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong>
        <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>
  